### ISSUE TITLE
Fix LAMDA property for calculating critical densities

### ISSUE THREAD

**Issue by pirg** [astropenguin/ndradex#30]
Hi, 
The following minimal example shows that the result for the computation of critical densities is different by several orders of magnitude between astroquery.lamda.utils.ncrit and ndradex.db.LAMDA.n_crit even thought ndradex uses astroquery.lamda.utils.ncrit and the tables seem to be identical.

Pierre

```
T_kin = 30

from ndradex.db import LAMDA
ncrit_from_ndradex = LAMDA('hco+@xpol').n_crit['1-0'](T_kin)

from astroquery.lamda.utils import ncrit
from astroquery.lamda import Lamda
tables = Lamda.query('hco+@xpol')
ncrit_from_astroquery = ncrit(tables,2,1,T_kin)

print("ncrit_from_ndradex: {:e}, ncrit_from_astroquery: {:e}".format(ncrit_from_ndradex,ncrit_from_astroquery.value))
```

**Comment by astropenguin** [comment]
This bug was fixed and the `n_crit` feature now works correctly (from v0.3.0). My apologies for keeping this issue for a long time...
