### ISSUE TITLE
ndradex 0.3.1 error after succesful installation

### ISSUE THREAD

**Issue by mgsantamaria** [astropenguin/ndradex#72]
After updating ndradex (succesfully), when doing import ndradex I get:

 File "/home/user/.local/lib/python3.8/site-packages/ndradex/__init__.py", line 29, in <module>
    radex.build()

  File "/home/user/.local/lib/python3.8/site-packages/ndradex/radex.py", line 100, in build
    sprun(

  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,

CalledProcessError: Command '['make', 'build', 'RADEX_LOGFILE=/dev/null', 'RADEX_MAXITER=999999']' returned non-zero exit status 2.

The previous versions of ndradex were working fine until I had to update astropy and numpy.

Is this a problem of my installation, or a problem of ndradex?

Thanks!

**Comment by astropenguin** [comment]
@mgsantamaria Thank you for reporting this issue! `CalledProcessError` means that building RADEX binaries from source was unsuccessful due to some problems. To investigate the issue further, could you run the following shell script in a terminal and check if you get some error messages?

```shell
$ cd /home/user/.local/lib/python3.8/site-packages/ndradex/bin
$ make build RADEX_LOGFILE=/dev/null RADEX_MAXITER=999999
```

**Comment by mgsantamaria** [comment]
@astropenguin thanks for your fast answer.

Doing that I get:

curl -fsO https://personal.sron.nl/~vdtak/radex/radex_public.tar.gz
/bin/sh: 1: curl: not found
make: *** [Makefile:56: radex-src] Error 127

**Comment by astropenguin** [comment]
@mgsantamaria Thank you for the detailed information. It seems that `curl` command is not installed on your machine or environment. Could you install it? (or if you cannot install it by some reasons, an alternative way is to (1) manually download `radex_public.tar.gz` and (2) put it in the `bin` directory.)
